---
cluster: 'sbatch -A {cluster.account} -p {cluster.partition} -n {cluster.n}  -t {cluster.time}'
cores: 1
jobs: 999
# Status command for cluster execution. This is only considered in combination with the –cluster flag.
# If provided, Snakemake will use the status command to determine if a job has finished successfully or failed.
# For this it is necessary that the submit command provided to –cluster returns the cluster job id.
# Then, the status command will be invoked with the job id. Snakemake expects it to return ‘success’
# if the job was successfull, ‘failed’ if the job failed and ‘running’ if the job still runs.
#cluster-status: '???'

#wrapper-prefix: https://bitbucket.org/snakemake/snakemake-wrappers/raw/

#default-resources: 'mem_mb=max(2*input.size, 1000)' 'disk_mb=max(2*input.size, 1000)'

# Set or overwrite values in the workflow config object. The workflow config object is accessible as variable config inside the workflow. Default values can be set by providing a JSON file (see Documentation).
#config: reference=reference.fasta
# Specify or overwrite the config file of the workflow (see the docs). Values specified in JSON or YAML format are available in the global config dictionary inside the workflow.
#configfile: config.yaml
# A JSON or YAML file that defines the wildcards used in ‘cluster’for specific rules,
# instead of having them specified in the Snakefile. For example, for rule ‘job’ you
# may define: { ‘job’ : { ‘time’ : ‘24:00:00’ } } to specify the time for rule ‘job’.
# You can specify more than one file. The configuration files are merged with later
# values overriding earlier ones.
cluster-config: cluster.yaml

# Specify working directory (relative paths in the snakefile will use this as their origin).
#directory: ./

#shadow-prefix: ./.snakemake

# This option is ignored when not in cluster mode.
#local-cores: 4

#report: report.html

# https://snakemake.readthedocs.io/en/stable/executable.html#CONDA
use-conda: True
#conda-prefix: .snakemake

#kubernetes: default
#kubernetes-env: []
#container-image: quay.io/snakemake/snakemake
...
