{
  "$id": "https://TGenNorth.github.io/nasp.schema.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Northern Arizona SNP Pipeline",
  "type": "object",
  "properties": {
    "reference": {
      "type": "string",
      "description": "TODO",
      "default": "reference.fasta"
    },
    "assemblies_dir": {
      "type": "string",
      "description": "TODO",
      "default": "assemblies"
    },
    "minimum_coverage": {
      "description": "TODO",
      "type": "integer",
      "minimum": 0,
      "default": 0
    },
    "minimum_coverage": {
      "description": "TODO",
      "type": "integer",
      "minimum": 0,
      "default": 10
    },
    "minimum_proportion": {
      "description": "TODO",
      "type": "number",
      "minimum": 0,
      "maximum": 1,
      "default": 0.9
    }
  }
}
